### ISSUE TITLE
Discovery fails exporting

### ISSUE THREAD

**Issue by seyedk** [awslabs/aws-discovery-utils#1]
when running the following command:

**python export.py --directory "/Code/Client/PDS/discovery-export" --start-time 2017-08-10T12:00 --end-time 2017-08-11T12:00 --filters o-0000fba8ca974c12d**
 it throws the following exception:

**Beginning export for 1 agents.
Starting export for agent o-0000fba8ca974c12d (1/1)
Traceback (most recent call last):
  File "export.py", line 187, in <module>
    count = start_exporting(count)
  File "export.py", line 64, in start_exporting
    raise(e)
AttributeError: 'ApplicationDiscoveryService' object has no attribute 'start_export_task'**

**Comment by mmarkoff** [comment]
Thanks Seyed. Please ensure that you have current versions of the boto modules - https://github.com/boto/botocore/releases, https://github.com/boto/boto3/releases. The export option used by this script was recently added to the Discovery API.
